language:	python
python:
    - 2.7

install:
    - wget -O - "https://github.com/gentoo/travis-repo-checks/archive/master.tar.gz" | tar -xz
    - bash travis-repo-checks-master/prepare-tests.bash

script:
    - bash travis-repo-checks-master/run-tests.bash
